FROM mcr.microsoft.com/playwright:v1.50.0-noble

RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list && \
    apt-get update --fix-missing && \
    apt-get install -y \
    xvfb \
    libappindicator3-1 \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*

COPY ./google-chrome-stable_90_amd64.deb /temp/google-chrome-stable_90_amd64.deb
RUN dpkg -i /temp/google-chrome-stable_90_amd64.deb || apt-get install -f -y

WORKDIR /app

COPY package.json tsconfig.json ./

RUN npm install

EXPOSE 3000

