name: Cypress Tests

on:
  push:
    branches:
      - feat/cypress
  pull_request:
    branches:
      - feat/cypress

jobs:
  test-chrome-90:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Setup Chrome 90
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 90.0.4430.212

      - name: Run Cypress tests on Chrome 90
        run: pnpm run cy:run --browser chrome

  test-chrome-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Setup Latest Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Run Cypress tests on Latest Chrome
        run: pnpm run cy:run --browser chrome
